[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "airtukt"
version = "0.1.0"
description = "ML tutorials for turbulence research"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "jupyterlab",
    "ipykernel"
]

[project.scripts]
airtukt = "airtukt.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
airtukt = [
    "tutorials/**/*.ipynb",
    "tutorials/**/*.py",
    "tutorials/**/*.csv",
    "tutorials/**/*.json",
    "tutorials/**/*.txt",
]
